@startuml RegistroManual
actor "__:Analista en Sismos__" as Analista

boundary "__:PantallaRegistrarResultado__" as PR

Analista --> PR : opcRegistrarResultado()

PR --> PR : abrirVentana()

control "__:GestorRegistrarResultado__" as GR

PR --> GR : nuevoResultado()

GR --> GR :buscarEventosSismicos()

entity "__:EventoSismico__" as ES #red

entity "__:EstadoES__" as EES
entity "__:select: EventoSismico__" as SES
group loop [Eventos sismicos auto detectados]
    GR --> ES : esAutoDetectado()
    ES --> EES : esAutoDetectado()
    GR --> ES : esPendienteRevision()
    ES --> EES : esPendienteRevision()

    GR --> ES : getDatosPrincipales()

    ES --> ES:  getFechaHoraOcurrencia()
    ES --> ES:  getLatitudEpicentro()
    ES --> ES:  getLongitudEpicentro()
    ES --> ES:  getLatitudHipocentro()
    ES --> ES:  getLongitudHipocentro()
    ES --> ES: getValorMagnitud()
end

GR --> GR : ordenarPorFechaYHora()
GR --> PR : mostrarEventosSismicos()

PR --> PR : pedirSeleccionEventoSismico()

Analista --> PR : tomarSeleccionEventoSismico()

PR --> GR : tomarSeleccionEventoSismico()

entity "__:Estado__" as E #red
GR --> GR : buscarEstadoBloqueado()
group loop [Mientras haya estados]
    GR --> E : esAmbitoEventoSismico()
    GR --> E : esBloqueadoEnRevision()
end

GR --> GR : getFechaHoraActual()

GR --> GR : buscarEmpleadoLogueado()

entity "__:Actual:Sesion__" as SA
entity "__:Log:Usuario__" as LU 

GR --> SA : buscarEmpleadoLogueado()
SA --> LU : getEmpleado()

GR --> GR : bloquearEvento()

entity "__:CambioEstado__" as CE #red

GR --> SES : revisar()

SES --> SES : buscarCambioEstado()
'Devuelve si es un verdadero o falso'
SES --> CE : *esActual()

entity "__:Actual:CambioEstado" as ACE #red
CE --> ACE : setFechaFin()

GR --> GR: crearCambioEstado()

create entity "__:nuevo:CambioEstado" as nCE 
GR --> nCE : new()

entity "__:Magnitud__" as M #red
entity "__:Clasificacion__" as C #red

entity "__:Origen__" as O #red
entity "__:Alcance__" as A #red

GR --> GR : buscarDatosSismicos()
GR --> SES: buscarDatosSismicos()

SES --> C: getNombre()
SES --> O: getNombre()
SES --> A: getNombre()

GR --> GR : buscarSerieTemporales()
group loop
    GR --> SES : buscarSerieTemporales()
    entity "__:SerieTemporal__" as ST #red
    entity "__:MuestraSismica__" as MS #red
    entity "__:DetalleMuestraSismica__" as DMS #red
    SES --> ST : getDatos()
    ST --> MS : getDatos()
    MS --> DMS : getDatos()
    entity "__:TipoDeDato__" as TDD #red
    
    DMS --> TDD : getDenominacion()


    create boundary "__:PantallaGenerarSismograma__" as PGS
    GR --> PGS : generarSismograma()
end

GR --> PR : mostrarDatosSismicos()

PR --> PR : habilitarOpcionVisualizacion()

PR --> PR :habilitarModificacionDatos()

PR --> PR : pedirSeleccionAccion()
Analista --> PR: tomarSeleccionAccion()

PR --> GR : tomarSeleccionAccion()
GR --> GR : validarSeleccionAccion()
GR --> GR : validarMagnitud()
GR --> SES : validarMagnitud()
SES --> M : *existeMagnitud()
GR --> GR : validarOrigen()
GR --> SES : validarOrigen()
SES --> O :*existeOrigen()
GR --> GR : validarAlcance()
GR --> SES : validarAlcance()
SES --> A : *existeAlcance()

GR --> GR : buscarEstadoRechazado()
group loop 
    GR --> E : esAmbitoEventoSismico()
    GR --> E : esRechazado()
end

GR --> GR : getFechaHoraActual()

create entity "__:nuevo:CambioEstado" as nCE
GR --> GR : crearCambioEstado() 
GR --> nCE : new()

PR --> PR : finCU()

@enduml