@startuml contrato

[*] --> EnRevision : new()

EnRevision --> Validado : validar()
Validado --> Firmado : ponerVigente()
Firmado --> Firmado : validarFecha( [Fecha Inicio Vigencia=false])
Firmado --> Vigente : validarFecha() [Fecha Inicio Vigencia=true]
Vigente --> Finalizado : finalizar [Renovo=NO]


Vigente --> Vigente : renovar() [Renovo=SI]

Vigente --> ConDeuda : adeudar()

ConDeuda --> Vigente : cobrar() [TiempoDeuda<3meses y el cliente pago]

ConDeuda --> ConDeuda : validarTiempoDeuda() [TiempoDeuda<3meses y el cliente no pago]

ConDeuda --> DeBaja : daDeBaja() [TiempoDeuda>3meses y el cliente no pago]

Vigente --> Cancelado : cancelar()

Vigente --> ConAccesoForzado : forzarAcceso()

ConAccesoForzado --> DeBaja : darDeBaja()

DeBaja --> [*]
Finalizado --> [*]
Cancelado -->[*]


@enduml

"ConAccesoForzado
Cancelado"