@startuml estado 

[*] --> Libre : new()

Libre --> NoDisponible : inhabilitar()
NoDisponible --> [*]
Libre --> Solicitado : asignarTurno()

Solicitado --> Solicitado : confirmarTurno() [Confirma=NO]


Solicitado --> Ocupado : confirmarTurno() [Confirma=SI]

Ocupado --> Derivado : derivarTurno()
Solicitado --> Cancelado : cancelar()
Ocupado --> Cancelado : cancelar()
Ocupado --> Asistio : asistio()
Ocupado --> NoAsistio : asisitio()
Ocupado --> Ocupado 
Derivado --> Asistio : asistio()
Derivado --> NoAsistio : asistio()

Asistio --> [*]
NoAsistio --> [*]
Cancelado --> [*]
@enduml