@startuml clase 

class CajaSeguridad{}


class AccesoForzado{}

class Cliente{}

class Rol{
    +nombre

}

class Contrato{}

class Estado{
    +ambito
    +nombre
    +esAmbito()
}
class CambioEstado{}

class SolicitudAccesoForzado{}

class TipoAccesoForzado{}

class Sesion{
    +fechaHoraInicio
    +fechaHoraFin
}
class Usuario{}

class Empleado{
    +nombre
    +apellido
}
class MotivoCancelacion{
    +nombre
}
class DetalleContrato{}
class TipoCajaSeguridad{
    +precio 
    +tamaño
}


CajaSeguridad --> "1" TipoCajaSeguridad : tipoCajaSeguridad
Contrato --> DetalleContrato : detalleContrato

DetalleContrato --> Cliente : cliente
Sesion --> "1" Usuario : usuario

Usuario --> "1" Empleado : empleado

AccesoForzado --> "1" TipoAccesoForzado : tipoAccesoForzado

DetalleContrato --> "1" Rol : rol

CambioEstado --> "1" Estado : estado
Contrato --> "1" Estado : estadoActual

Contrato --> "1..*" CambioEstado : cambioEstado

CajaSeguridad --> "1" Contrato : contrato

CajaSeguridad --> "1" Estado : estado
CajaSeguridad --> "1..*" AccesoForzado : accesoForzado



Contrato ..> CajaSeguridad

CambioEstado --> "1" Usuario: usuario
AccesoForzado --> "1..*" SolicitudAccesoForzado: solicitudAccesoForzado 

SolicitudAccesoForzado --> "1..*" Contrato : contrato

CambioEstado --> "1" MotivoCancelacion : motivoCancelacion
Cliente ..> DetalleContrato
@enduml