@startuml

class Contrato{
-fechaInicio
-fechaFin
}

class CajaDeSeguridad{
-nroCaja
-tipo
-seguroIncluido
}

class CambioEstado{
-fechaHoraInicio
-fechaHoraFin
}

class Estado{
-ambito
-valor
}

class Cliente{
-esTitular
-nombre
-apellido
-DNI
-PINAcceso
}

class MotivoCancelacion{
-nombre
-descripcion
}
class SolicitudCancelacion{
-fechaHora
}

class Sesion{
    -fechaHoraInicio
    -fechaHoraFin
    -usuario:Usuario
}
class Usuario{
    -nombreUsuario
    -contraseña
    -nroTelefono
    -responsable:Responsable
}
class Responsable{
    -nombre
    -apellido 
    -DNI
}

class Gestor{
-DNITitular
-listaContratosVigentes
-listaOrdenadaContratos
-contratoSeleccionado
-antiguedadContrato
-fechaHoraActual
-listaSolicitudesCancelacion
-declaracionVaciamiento
-listaMotivosCancelacion
-motivoSeleccionado
-punteroEstadoCencelado
-punteroEstadoDisponible

} 
class Pantalla{
-btnCancelar
-btnConfirmar
-txtDNITitular
-gridContratosVigentesOrdenados
-arrayMotivosCancelacion

}


Sesion --> "1" Usuario
Usuario --> "1" Responsable

Gestor ..> Sesion
Gestor ..> Pantalla
Pantalla ..> Gestor
Gestor..> Contrato
Gestor ..> Cliente

Contrato --> "1..* clientes" Cliente
Contrato --> "0..* solicitudes" SolicitudCancelacion
SolicitudCancelacion --> "1 titular" Cliente
Contrato --> "1 motivo" MotivoCancelacion
Contrato --> "1.. estadoContrato" CambioEstado
CambioEstado --> "1 estado" Estado

Contrato --> "1 cajaSeguridad" CajaDeSeguridad
CajaDeSeguridad --> "1 estado" Estado

@enduml