@startuml detalleClase

class Pantalla{
    +labelClienteTitular
    +listaContratosVigentes
    +listaMotivosCancelacion
    +btnConfirmar()
    +btnCancelar()
}
class Gestor{
    +punteroCliente
    +listaContratosVigentes
    +dniTitular
    +contratoSeleccionado
    +listaMotivosCancelacion
    +responsableLogueado
    +punteroEstadoCancelado
    +punteroEstadoDisponible
    +fechaHoraActual
    +motivoSeleccionad
}
class Sesion{
    +fechaHoraInicio
    +fechaHorsFin
}
class Usuario{
    +nombreUsuario
    +contraseña
    +nroTelefono
    +getResponsable()
}
class Responsable{
    +nombre
    +apellido
    +dni
}
class CLiente{
    +nombre
    +apellido
    +dni
}
class MotivoCancelacion{
    +nombre
    +descripcion
    +getNombre()
}
class CajaSeguridad{
    +num
}
class Contrato{}
class DetalleCOntrato{}
class Rol{
    +nombre
}
class CambioEstado{
    +fechaHoraInicio
    +fechaHoraFin
}
class Estado{
    +nombre
    +ambito
}
class SolicitudCancelacion{
    +fechaHora
}

Gestor ..> Pantalla 
Pantalla ..> Gestor
Gestor ..> Sesion
Sesion--> "1" Usuario : usuario
Usuario --> "1" Responsable : responsable

Gestor ..> Contrato
Contrato *-> "1..6" DetalleCOntrato: detalleCOntrato

DetalleCOntrato --> "1" Rol : rol
DetalleCOntrato --> "0..1" SolicitudCancelacion : solicitudCancelacion

Contrato --> "1" CajaSeguridad : cajaSeguridad

CambioEstado --> "1" Estado: estado

DetalleCOntrato --> "1" CLiente : cliente

CambioEstado --> "1" MotivoCancelacion : motivoCancelacion


Contrato --> "1..*" CambioEstado: cambioEstado

CajaSeguridad --> "1" Estado : estado
Contrato --> "1" Estado : estado

CambioEstado --> "1" Responsable : responsable
@enduml